apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- retool-code-executor-container.yaml
- retool-container.yaml
- retool-jobs-runner.yaml
- retool-postgres.yaml
- retool-workflows-backend-container.yaml
- retool-workflows-worker-container.yaml
images:
  # These should be set to the same version
- name: tryretool/code-executor-service
  newTag: 3.x.x
- name: tryretool/backend
  newTag: 3.x.x
configMapGenerator:
- name: retool-config
  envs:
  - retool.env
  - retool-temporal.env
  - retool-postgres.env
