apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- retool-code-executor-container.yaml
- retool-container.yaml
- retool-jobs-runner.yaml
- retool-postgres.yaml
- retool-workflows-backend-container.yaml
- retool-workflows-worker-container.yaml
