apiVersion: v1
kind: Secret
metadata:
  name: retoolsecrets
type: Opaque
data:
  jwt_secret: {{ random base64 encoded string to sign jwt tokens }}
  encryption_key: {{ random base64 encoded string to encrypt database credentials }}
  postgres_password: {{ random base64 encoded string to set as the internal retool db password }}
stringData:
  license_key: {{ license key Retool will provide you }}
  google_client_id: {{ google client id }}
  google_client_secret: {{ google client secret }}
