apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../kubernetes
patches:
  - path: retool-container.yaml
images:
  # Configure this file with the latest stable release
- name: tryretool/code-executor-service
  newTag: 3.x.x-stable
- name: tryretool/backend
  newTag: 3.x.x-stable
configMapGenerator:
- name: retool-config
  behavior: merge
  envs:
  - overrides.env
